### ISSUE TITLE
Starting workflow with "php tailwind.php..." doesnt work

### ISSUE THREAD

**Issue by mhoffmann-app** [clnt/alfred-tailwindcss-docs#11]
Assuming "php" exists no longer works on MacOs Monterey. Please use solution of tailwind workflow:

`if [ -f "/opt/homebrew/bin/php" ]; then
    /opt/homebrew/bin/php tailwindcss.php "{query}"
elif [ -f "/usr/local/bin/php" ]; then
    /usr/local/bin/php tailwindcss.php "{query}"
elif [ -f "/usr/bin/php" ]; then
    /usr/bin/php tailwindcss.php "{query}"
fi`

**Comment by clnt** [comment]
Hi @mhoffmann-app 

Have you downloaded the latest release tagged 2.0.1 and deleted existing workflow before re-adding it?

I have already implemented the script to detect PHP locations on that release and have also tested it on PHP 8.1 release today.

The download link in the readme will give you the latest release.

Cheers

**Comment by mhoffmann-app** [comment]
I just downloaded it for the first time. I read that Alfred 4.6.1 added `/opt/local/bin` for Monterey, but I installed php via homebrew. Tailwind workflow checks also for `/opt/homebrew/bin`.

**Comment by clnt** [comment]
@mhoffmann-app 

It should be working fine it has been tested on macs running Monterey on both Intel and M1 chips - and also works with older versions of macOS, I myself am running both Homebrew installs.

The script and paths you are referring to are here in the `info.plist` file which makes up the workflow: https://github.com/clnt/alfred-tailwindcss-docs/blob/957ba67ac5b88467d29609364d1c56e7c0bb7bee/info.plist#L108

This is a related issue where it was first reported #9 and fixed with #10 

Ensure when you do `which php` in your terminal that it gives you the expected path back.

**Comment by mhoffmann-app** [comment]
WTF?!? Noooo, i have confused Tailwind and Livewire Workflows... Sorry! :( I opened an issue in the wrong repo... YOU have a nice solution which works very well. Thumps up!

**Comment by clnt** [comment]
No problem, closing issue :) thanks!

**Comment by mgussekloo** [comment]
Hi! I got deprecated warnings when using PHP 8.4. Maybe we could add a "hide warnings" flag to this workflow?
E.g.

/opt/homebrew/bin/php -d error_reporting=0 tailwindcss.php "{query}"

fixed my issues.
