### ISSUE TITLE
Doesn't work with v0 documentation

### ISSUE THREAD

**Issue by damcclean** [clnt/alfred-tailwindcss-docs#3]
This Alfred workflow doesn't seem to work with the v0 Tailwind CSS docs.

The workflow keeps directing links to: https://v0.tailwindcss.com

But the v0 documentation is now located at: https://tailwindcss-v0.netlify.app/

Looks like it might be something to do with the Algolia search stuff.

**Comment by clnt** [comment]
Thanks for making me aware 👍 will get this sorted out in a few hours when I can look at it

**Comment by clnt** [comment]
Having some issues at the moment getting this to work and unfortunately the index has gone a bit crazy upon updating it to index the new URL, which is odd as I haven't changed the selection config at all since it was made and everything pretty much looks the same markup wise apart from a couple of things I've noticed such as the links on the site:

<img width="376" alt="Screenshot 2020-10-19 at 18 12 53" src="https://user-images.githubusercontent.com/19330442/96489883-f520c980-1237-11eb-9622-67bc9852ff55.png">

Might need to reach out to Algolia and see if they can assist in getting the configuration working, or if anyone else has experience with Algolia DocSearch then feel free to make a suggestion.

Here is the current DocSearch configuration file:

```
{
  "index_name": "v0_tailwindcss",
  "start_urls": [
    "https://tailwindcss-v0.netlify.app/docs"
  ],
  "stop_urls": [],
  "selectors": {
    "lvl0": {
      "selector": "//nav[contains(@id, 'nav')]//a[contains(@class, 'font-semibold')][1]/preceding::p[1]",
      "type": "xpath",
      "global": true,
      "default_value": "Documentation"
    },
    "lvl1": ".markdown h1",
    "lvl2": ".markdown h2",
    "lvl3": ".markdown h3",
    "lvl4": ".markdown h4",
    "lvl5": ".markdown h5",
    "text": ".markdown p, .markdown li"
  }
}
```

Seems to be managing the main docs site fine still but something is preventing it from indexing everything, weirdly it seems to only report on two routes when running DocSearch:

<img width="704" alt="Screenshot 2020-10-19 at 18 30 31" src="https://user-images.githubusercontent.com/19330442/96490818-3c5b8a00-1239-11eb-8ff1-3a2e2d635860.png">

**Comment by clnt** [comment]
Update on things:

Did a test using their latest scraper and a new configuration, still getting the same issues with v0 docs so I have raised this with Algolia who are looking into the DocSearch configuration and said they would notify me once it is fixed.

One benefit that came out of the testing was that the main docs site index for v1+ built with the new configuration has gained much more records which should give better search results, I plan on updating the main index to use this soon.

Luckily the fix won't need an update to the Alfred workflow itself, just need to wait for an updated configuration to power the index.

**Comment by Shipow** [comment]
Hello, I've found the issue on Tailwind config, here is my quick fix for reference. I'll submit the case to Tailwind team.

#Demo
https://codesandbox.io/s/docsearchv3-tailwindcss-olm3i?file=/src/App.js

#Config
`{
  "index_name": "tailwindcss",
  "start_urls": [
    {
      "url": "https://tailwindcss.com/",
      "selectors_key": "v1",
      "extra_attributes": {
        "version": [
          "v1"
        ]
      }
    },
    {
      "url": "https://tailwindcss-v0.netlify.app/docs/",
      "extra_attributes": {
        "version": [
          "v0"
        ]
      }
    },
    {
      "url": "https://tailwindcss-v0.netlify.app//docs/",
      "extra_attributes": {
        "version": [
          "v0"
        ]
      }
    }
  ],
  "stop_urls": [],
  "selectors": {
    "default": {
      "lvl0": {
        "selector": "//nav[contains(@id, 'nav')]//a[contains(@class, 'font-semibold')][1]/preceding::p[1]",
        "type": "xpath",
        "global": true,
        "default_value": "Documentation"
      },
      "lvl1": ".markdown h1",
      "lvl2": ".markdown h2",
      "lvl3": ".markdown h3",
      "lvl4": ".markdown h4",
      "lvl5": ".markdown h5",
      "text": ".markdown > p, .markdown > ul li, .markdown td:first-child, .markdown .text-xl"
    },
    "v1": {
      "lvl0": {
        "selector": "//nav[contains(@id, 'nav')]//*[contains(@class, 'opacity-25')][1]/preceding::h5[1]",
        "type": "xpath",
        "global": true,
        "default_value": "Documentation"
      },
      "lvl1": ".markdown h1",
      "lvl2": ".markdown h2",
      "lvl3": ".markdown h3",
      "lvl4": ".markdown h4, .markdown td:first-child",
      "lvl5": ".markdown h5",
      "text": ".markdown > p, .markdown > ul li, .markdown td:not(:first-child), .markdown .text-gray-600"
    }
  },
  "selectors_exclude": [
    "p.text-base",
    ".list-inside",
    ".bg-gray-200"
  ],
  "custom_settings": {
    "attributesForFaceting": [
      "version",
      "type",
      "tags"
    ],
    "attributesToRetrieve": [
      "hierarchy",
      "content",
      "anchor",
      "url",
      "url_without_anchor",
      "type"
    ],
    "separatorsToIndex": "@_"
  },
  "conversation_id": [
    "459164857"
  ],
  "nb_hits": 11019
}`

**Comment by clnt** [comment]
@damcclean 

Both indexes updated with latest configuration, results much better and v0 now working again 👍 

Thanks for your support @Shipow

**Comment by damcclean** [comment]
Awesome, thanks for the bugfix. I can confirm it's now working. 👍  Have a nice day!
