### ISSUE TITLE
Alfred v3 incompatible

### ISSUE THREAD

**Issue by henryavila** [clnt/alfred-tailwindcss-docs#6]
Hi, I'm using the Alfred v3 last update, but when I try to use this workflow, I get this error:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/8429941/100222671-31aba900-2ef9-11eb-9d1f-9abc7e017427.png">

Here is the v3 version
<img width="713" alt="image" src="https://user-images.githubusercontent.com/8429941/100222761-543dc200-2ef9-11eb-9478-d2a7956ef465.png">

**Comment by clnt** [comment]
@henryavila Thanks for bringing this to my attention, I will do some testing with Alfred 3 and report back as soon as I can

**Comment by clnt** [comment]
@henryavila Apologies for such a delay in getting back to you.

Unfortunately I cannot remember the email I used when I created the workflow in Alfred 3, and between Alfred 3 and 4 there have been fundamental changes to the how the workflows are built/formatted under the hood as I have been told from contacting them.

In order for me to maintain an Alfred 3 build of this I would probably need to purchase another licence for Alfred 3, and use a VM to create the build as the two versions of Alfred cannot be run side-by-side.

There hasn't been any further comments on this issue so I am not sure how many Alfred 3 users there are still using this, or simply haven't used it due to it not working on Alfred 3.

### It would be good to gain some feedback if I am to look at obtaining another licence in order to maintain an Alfred 3 workflow build otherwise the workflow will need to become Alfred 4 only, please react with a thumbs up or comment if you require Alfred 3 support.

**Comment by henryavila** [comment]
Hi @clnt I upgraded to Alfred v4 and its working fine. Thanks
