### ISSUE TITLE
Results became not accurate recently? 🤔

### ISSUE THREAD

**Issue by dmitry-ivanov** [clnt/alfred-tailwindcss-docs#7]
Hi,

First of all, thank you for the great workflow you've created! 👍

Just wanted to mention that recently results became not accurate for me... 🤔

For example, when I search for "height", there's no link to the main "Height" page at all:

![1-height-workflow](https://user-images.githubusercontent.com/1286821/134334806-7bd3fdd9-2f3b-4b0b-99e2-9b9293c3e091.jpg)

If you use website's search - you'll find it, though:

![2-height-website](https://user-images.githubusercontent.com/1286821/134334907-ac728633-35a7-4994-a368-45dc3428247d.jpg)

Even more interesting results if you try "h-10":

![2-h-10-workflow](https://user-images.githubusercontent.com/1286821/134334950-81091707-f28b-49fa-9093-da77de44a2b2.jpg)

Do you have any ideas?

Thank you!

**Comment by lukasklein** [comment]
Hey @dmitry-ivanov, I think I found the issue. You can fix it for yourself by going into the Alfred Workflows settings, right-click onto the TailwindCSSDocs workflow and select "Open in Finder"
![image](https://user-images.githubusercontent.com/1492869/135421440-401065b6-79b4-416b-8480-d0eb82a098d2.png)

Locate the `tailwindcss.php` file and replace `v2_tailwindcss` in line 20 with just `tailwindcss`.

**Comment by clnt** [comment]
Hi @dmitry-ivanov 

Thanks for bringing this to my attention, I will have to do some digging to find a solution because from what I can see the the TailwindCSS docsearch config file has not changed since February (the same config that the tailwind site uses or at least should be).

My docsearch config is not like for like exactly, I have a config for each index (v0 (doesn't get updated)/v1 and v2). But in terms of the selectors they are using they match up with the main TailwindCSS docsearch config.

Thanks,
Matt

**Comment by clnt** [comment]
Hi @dmitry-ivanov 

Well this was odd, so the index contained about half the records it should have done when my server last updated it. I just logged into it and cleared out all existing Docker containers, then I ran a manual update into a different index as a test and it has indexed double the amount of records and now the results make sense again (which when nothing has 'changed', I would expect :D) 

I have now updated the main `v2_tailwindcss` index.

When performing the same test you carried out above:

![Screenshot 2021-10-02 at 12 43 47](https://user-images.githubusercontent.com/19330442/135714783-015dbd8e-a628-475e-bde8-bc2a6399e749.png)

Thanks,
Matt
